title: C2W Publications
description: Marxist-Leninist-Maoist Publisher which seeks to proliferate and disseminate important texts to inform the practice and action of revolutionaries and progressives.
show_downloads: true
google_analytics:
theme: jekyll-theme-dinky